#!/bin/bash

# MagicBlock Dev Skill - Build Script
# Produces flattened single-file artifacts in dist/ for use across multiple agents.
#
# Outputs:
#   dist/AGENTS.md              - Full flattened skill (cross-tool standard)
#   dist/system-prompt.md       - Trimmed SKILL.md + reference links (chat-only platforms)
#   dist/magicblock.cursor.mdc  - Cursor-formatted rule with .mdc frontmatter
#   dist/magicblock.zip         - Zipped skill/ folder (for Claude.ai upload)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$SCRIPT_DIR/skill"
DIST_DIR="$SCRIPT_DIR/dist"
SKILL_NAME="magicblock"
REPO_URL="https://github.com/magicblock-labs/magicblock-dev-skill"

# File order matches SKILL.md's "Progressive disclosure" section
REFERENCES=(
    "delegation.md"
    "magic-actions.md"
    "lamports-topup.md"
    "typescript-setup.md"
    "cranks.md"
    "vrf.md"
    "private-payments.md"
    "resources.md"
)

# Strip YAML frontmatter (--- delimited block at top of file)
strip_frontmatter() {
    local file="$1"
    awk '
        BEGIN { in_fm = 0; fm_done = 0; line_count = 0 }
        {
            line_count++
            if (line_count == 1 && /^---$/) { in_fm = 1; next }
            if (in_fm && /^---$/) { in_fm = 0; fm_done = 1; next }
            if (in_fm) next
            print
        }
    ' "$file"
}

# Extract first H1 heading from a file (after frontmatter)
extract_title() {
    local file="$1"
    strip_frontmatter "$file" | grep -m 1 "^# " | sed 's/^# //'
}

# Build AGENTS.md - full flattened version
build_agents_md() {
    local out="$DIST_DIR/AGENTS.md"
    {
        echo "<!-- Auto-generated by build.sh from $REPO_URL -->"
        echo "<!-- Source of truth: skill/SKILL.md and skill/*.md in the repo above -->"
        echo ""
        strip_frontmatter "$SKILL_DIR/SKILL.md"
        for ref in "${REFERENCES[@]}"; do
            local ref_path="$SKILL_DIR/$ref"
            if [ ! -f "$ref_path" ]; then
                echo "Warning: missing reference file: $ref" >&2
                continue
            fi
            echo ""
            echo "---"
            echo ""
            strip_frontmatter "$ref_path"
        done
    } > "$out"
    local size=$(wc -c < "$out" | tr -d ' ')
    echo "Built: $out ($size bytes)"
}

# Build system-prompt.md - SKILL.md only + footer with reference URLs
# Optimized for chat-only platforms with limited context budget.
build_system_prompt() {
    local out="$DIST_DIR/system-prompt.md"
    {
        echo "<!-- Trimmed system prompt for chat-only platforms (DeepSeek, ChatGPT default, etc.) -->"
        echo "<!-- For the full skill including reference patterns, see $REPO_URL -->"
        echo ""
        strip_frontmatter "$SKILL_DIR/SKILL.md"
        echo ""
        echo "---"
        echo ""
        echo "## Reference patterns (fetch when needed)"
        echo ""
        echo "If the user's question involves a specific topic below, fetch the corresponding file from the repo for deeper guidance:"
        echo ""
        for ref in "${REFERENCES[@]}"; do
            local ref_path="$SKILL_DIR/$ref"
            if [ ! -f "$ref_path" ]; then continue; fi
            local title
            title=$(extract_title "$ref_path")
            if [ -z "$title" ]; then title="$ref"; fi
            echo "- [\`$ref\`]($REPO_URL/blob/main/skill/$ref) — $title"
        done
    } > "$out"
    local size=$(wc -c < "$out" | tr -d ' ')
    echo "Built: $out ($size bytes)"
}

# Build Cursor .mdc with Cursor-specific frontmatter
build_cursor_mdc() {
    local out="$DIST_DIR/$SKILL_NAME.cursor.mdc"
    {
        cat <<'EOF'
---
description: MagicBlock Ephemeral Rollups development patterns for Solana — delegation flows, Magic Actions, dual-connection architecture, cranks, VRF, lamports top-up, commit sponsorship, and private payments with swaps. Use when working on MagicBlock or Ephemeral Rollups.
globs:
alwaysApply: false
---
EOF
        echo ""
        strip_frontmatter "$SKILL_DIR/SKILL.md"
        for ref in "${REFERENCES[@]}"; do
            local ref_path="$SKILL_DIR/$ref"
            if [ ! -f "$ref_path" ]; then continue; fi
            echo ""
            echo "---"
            echo ""
            strip_frontmatter "$ref_path"
        done
    } > "$out"
    local size=$(wc -c < "$out" | tr -d ' ')
    echo "Built: $out ($size bytes)"
}

# Build zip for Claude.ai upload
build_zip() {
    local out="$DIST_DIR/$SKILL_NAME.zip"
    if ! command -v zip >/dev/null 2>&1; then
        echo "Warning: 'zip' command not found, skipping $out"
        return 0
    fi
    rm -f "$out"
    (cd "$SCRIPT_DIR" && zip -r -q "$out" "skill/" -x "*.DS_Store" -x "**/.DS_Store")
    local size=$(wc -c < "$out" | tr -d ' ')
    echo "Built: $out ($size bytes)"
}

# Main
if [ ! -d "$SKILL_DIR" ]; then
    echo "Error: skill/ directory not found at $SKILL_DIR"
    exit 1
fi

if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
    echo "Error: skill/SKILL.md not found"
    exit 1
fi

echo "Building dist/ artifacts from skill/..."
rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"

build_agents_md
build_system_prompt
build_cursor_mdc
build_zip

echo ""
echo "Done. Artifacts:"
ls -1 "$DIST_DIR"
